paths-ignore:
  - **/docs/**
  - dist/*.js

# Create the necessary file in the repository to exclude the following files from being scanned:
# 
# Any file in a docs directory anywhere in the repository.
# All js files in a dist folder at the root of the repository.
